---
# - name: ensure fzf directory exists
#   file:
#     path: "{{ fzf_path }}"
#     state: directory
#     mode: 0644
#     owner: "{{ user }}"
#     group: "{{ user }}"
#     recurse: true

- name: ensure fzf is cloned
  git:
    repo: "{{ fzf_repo }}"
    dest: "{{ fzf_path_git }}"
    depth: "1"
  become_user: "{{ user }}"
  become: true

- name: set fzf install command generate rc
  set_fact:
    fzf_cmd_rc: "{% if fzf_update_rc %}--update-rc{% else %}--no-update-rc{% endif %}"
  check_mode: false

- name: set fzf install command shell completion
  set_fact:
    fzf_cmd_comp: "{% if fzf_completion %}--completion{% else %}--no-completion{% endif %}"
  check_mode: false

- name: set fzf install command key bindings
  set_fact:
    fzf_cmd_key: "{% if fzf_key_bindings %}--key-bindings{% else %}--no-key-bindings{% endif %}"
  check_mode: false

- name: ensure fzf install script is run
  command: "{{ fzf_path_git }}/install --bin"
  changed_when: false
  become_user: "{{ user }}"
  become: true

- name: ensure fzf configure script is run
  command: "{{ fzf_path_git }}/install {{ fzf_cmd_rc }} {{ fzf_cmd_comp }} {{ fzf_cmd_key }}"
  changed_when: false
  become_user: "{{ user }}"
  become: true
  when: not fzf_template

- name: custom config paths
  include_tasks: fzf_config.yml
  when: fzf_template
