---
- name: Converge
  hosts: all
  vars:
    - user: molecule
      user_home: /home/molecule/

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600

    - name: ensure preReq pckgs are installed
      apt:
        name:
          - git
          - curl
          - wget
          - vim
        state: present

    - name: create test user
      user:
        name: molecule

  tasks:
    - name: "Include ansible-role-fzf"
      include_role:
        name: "ansible-role-fzf"
